export type DownloadStatus = "pending" | "downloading" | "completed" | "error";
export type Format = "mp3" | "mp4" | "mp4-hd";

export interface DownloadItem {
  id: string; // UUID generated by frontend or backend
  url: string;
  title: string; // Fetched from yt-dlp
  format: Format;
  status: DownloadStatus;
  progress: number; // 0 to 100
  errorMsg?: string;
  filePath?: string; // For "Play" and "Open in folder"
}

export interface AppSettings {
  videoFolder: string;
  audioFolder: string;
  maxConcurrent: number;
}
